// src/components/navbar/NavBar.svelte
<script lang="ts">
  import type { NavItemType } from "./NavTypes";
  import { onMount } from "svelte";
  import { initTheme, toggleTheme } from "./helpers/theme";
  import LeftNavBtn from "./LeftNavBtn.svelte";
  import MenuBar from "./MenuBar.svelte";
  import RightNavBar from "./RightNavBar.svelte";

  interface Props {
    name: string;
    navLinks?: NavItemType[];
    clickToggleCallback?: (state: boolean) => void;
    onSearch?: () => void;
  }

  const {
    name,
    navLinks = [],
    clickToggleCallback = () => {},
    onSearch = () => {},
  }: Props = $props();

  let showNav = $state(true);
  let atTop = $state(true);
  let isDark = $state(false);

  onMount(() => {
    if (typeof window === "undefined" || typeof document === "undefined")
      return;

    // Initialize theme based on storage or system preference
    const currentTheme = initTheme(document, window);
    isDark = currentTheme === "dark";

    let lastScroll = window.scrollY;
    atTop = lastScroll <= 0;
    let ticking = false;

    const handleScroll = () => {
      if (ticking) return;

      ticking = true;
      window.requestAnimationFrame(() => {
        const current = window.scrollY;
        if (current > lastScroll) showNav = false;
        else if (current < lastScroll) showNav = true;

        lastScroll = current;
        atTop = current <= 0;
        ticking = false;
      });
    };

    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => window.removeEventListener("scroll", handleScroll);
  });

  const handleToggleTheme = () => {
    if (typeof document === "undefined" || typeof window === "undefined")
      return;

    const next = toggleTheme(document, window, isDark ? "dark" : "light");
    isDark = next === "dark";
  };

  const handleSearch = () => onSearch?.();
</script>

<nav
  id="nav"
  class={`h-12.5 fixed top-0 w-full z-9 backdrop-blur-8 backdrop-saturate-180 ${atTop ? "nav-top" : "nav-bg"}`.trim()}
  style={showNav ? "" : "transform: translateY(-100%);"}
>
  <div
    class="mb-0 ml-auto mr-auto mt-0 flex flex-nowrap h-full w-[calc(100%-0.625rem)] w-85%"
  >
    <LeftNavBtn clickCallback={clickToggleCallback} />
    <MenuBar {name} {navLinks} />
    <RightNavBar>
      <li>
        <button
          type="button"
          class="text-5 pb-2.5 pl-2 pr-2 pt-2.5 border-none bg-transparent cursor-pointer"
          onclick={handleToggleTheme}
          aria-label="Toggle theme"
        >
          <div class={isDark ? "i-ri-moon-line" : "i-ri-sun-line"}></div>
        </button>
      </li>
      <li>
        <button
          type="button"
          id="search"
          class="text-5 pb-2.5 pl-2 pr-2 pt-2.5 border-none bg-transparent cursor-pointer"
          onclick={handleSearch}
          aria-label="Search"
        >
          <div class="i-ri-search-line"></div>
        </button>
      </li>
    </RightNavBar>
  </div>
</nav>

<style>
  #nav {
    transition: transform 0.4s ease;
  }

  .nav-bg {
    background-image: var(--nav-bg);
    box-shadow: 0.1rem 0.1rem 0.2rem var(--grey-9-a1);
    text-shadow: 0 0 0.0625rem var(--grey-9-a1);
    color: var(--text-color);
  }

  .nav-top {
    color: var(--header-text-color);
    background-image: linear-gradient(
      180deg,
      rgba(0, 0, 0, 0.45) 0%,
      rgba(0, 0, 0, 0.2) 45%,
      rgba(0, 0, 0, 0) 100%
    );
    text-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.5);
  }
</style>

// packages/astro-theme-shokax/src/components/navbar/NavBar.vue
<script lang="ts" setup>
import type { NavItemType } from './NavTypes'
import { useDark, useWindowScroll } from '@vueuse/core'
import { computed } from 'vue'
import LeftNavBtn from './LeftNavBtn.vue'
import MenuBar from './MenuBar.vue'
import RightNavBar from './RightNavBar.vue'

const props = defineProps<{
  name: string
  navLinks: NavItemType[]
  clickToggleCallback: (state: boolean) => void
}>()

defineEmits<{
  clickSearch: []
}>()

const { directions, arrivedState } = useWindowScroll({ throttle: 10 })

let scrollFlag = true

const showNav = computed(() => {
  if (directions.bottom) {
    scrollFlag = false
    return false
  }
  else if (directions.top) {
    scrollFlag = true
    return true
  }
  else {
    return scrollFlag
  }
})

const isDark = useDark({
  selector: 'html',
  attribute: 'data-theme',
  valueDark: 'dark',
  valueLight: 'light',
})
</script>

<template>
  <Transition name="slideDownIn">
    <nav
      v-show="showNav" id="nav" :class="{ 'nav-bg': !arrivedState.top }"
      class="h-12.5 w-full top-0 fixed z-9 backdrop-blur-8 backdrop-saturate-180"
    >
      <div class="mb-0 ml-auto mr-auto mt-0 flex flex-nowrap h-full w-[calc(100%-0.625rem)] w-85%">
        <LeftNavBtn :click-callback="clickToggleCallback" />
        <MenuBar :name="name" :nav-links="props.navLinks" />
        <RightNavBar>
          <div class="text-5 pb-2.5 pl-2 pr-2 pt-2.5 cursor-pointer" @click="isDark = !isDark">
            <div :class="{ 'i-ri-sun-line': !isDark, 'i-ri-moon-line': isDark }" />
          </div>
          <div id="search" class="text-5 pb-2.5 pl-2 pr-2 pt-2.5 cursor-pointer" @click="$emit('clickSearch')">
            <div class="i-ri-search-line" />
          </div>
        </RightNavBar>
      </div>
    </nav>
  </Transition>
</template>

<style lang="css" scoped>
.nav-bg {
  background-image: var(--nav-bg);
  box-shadow: 0.1rem 0.1rem 0.2rem var(--grey-9-a1);
  text-shadow: 0 0 0.0625rem var(--grey-9-a1);
  color: var(--text-color);
}

@keyframes slideDownIn {
  0% {
    transform: translateY(-4rem);
  }
  100% {
    transform: translateY(0);
  }
}

@keyframes slideUpOut {
  0% {
    transform: translateY(0);
  }
  100% {
    transform: translateY(-4rem);
  }
}

.slideDownIn-enter-active {
  animation: 0.4s slideDownIn;
}

.slideDownIn-leave-active {
  animation: 0.4s slideUpOut;
}
</style>
