// src/components/navbar/NavLinkItem.svelte
<script lang="ts">
  import NavItem from "./NavItem.svelte";

  interface Props {
    href?: string;
    text?: string;
    icon?: string | null;
    class?: string;
    [key: string]: any;
  }

  const {
    href = "#",
    text,
    icon = null,
    class: className = "",
  }: Props = $props();

  const iconClasses = $derived(
    icon ? `${icon} icon-nav text-xl vertical-text-bottom inline-block` : "",
  );
  const mergedClass = $derived([className].filter(Boolean).join(" "));
</script>

<NavItem class={mergedClass}>
  <a {href}>
    {#if icon}
      <div class={iconClasses}></div>
    {/if}
    {text}
  </a>
</NavItem>

// packages/astro-theme-shokax/src/components/navbar/NavLinkItem.vue
<script setup lang="ts">
import NavItem from './NavItem.vue'

const props = defineProps<{
  href?: string
  text?: string
  icon?: string
}>()

const linkHref = props.href || '#'
</script>

<template>
  <NavItem>
    <a :href="linkHref">
      <div v-if="icon" :class="icon" class="icon-nav text-xl vertical-text-bottom inline-block" />
      {{ text }}
    </a>
  </NavItem>
</template>
