// packages/astro-theme-shokax/src/components/navbar/MenuBar.vue
<script setup lang="ts">
import type { NavItemType } from './NavTypes'
import { useWindowSize } from '@vueuse/core'
import DropBox from './DropBox.vue'
import NavLinkItem from './NavLinkItem.vue'

const props = defineProps<{
  navLinks: NavItemType[]
  name: string
}>()

const { width } = useWindowSize()
</script>

<template>
  <ul class="m-0 pb-2.5 pt-2.5 p-is-0 w-full">
    <NavLinkItem :class="{ 'inline-block': width > 820, 'block': width <= 820 }" href="/" :text="name" />
    <template v-if="width > 820">
      <template v-for="({ href, text, icon, dropbox, dropboxItems }) in props.navLinks" :key="href">
        <NavLinkItem
          v-if="!dropbox" :href="href" :text="text" :icon="icon"
          class="linkTransition inline-block before:rounded-0.5 before:bg-current before:h-0.75 before:w-0 before:content-empty before:transform-translate-x--50% before:bottom-0 before:left-50% before:absolute hover:before:w-60%"
        />
        <DropBox v-else :nav-links="dropboxItems!" :icon="icon" :root-text="text" class="inline-block" />
      </template>
    </template>
  </ul>
</template>

<style lang="css" scoped>
.linkTransition::before {
  transition: all 0.4s ease-in-out;
}
</style>

// src/components/navbar/MenuBar.svelte
<script lang="ts">
  import type { NavItemType } from "./NavTypes";
  import DropBox from "./DropBox.svelte";
  import NavLinkItem from "./NavLinkItem.svelte";

  interface Props {
    navLinks?: NavItemType[];
    name: string;
  }

  const { navLinks = [], name }: Props = $props();
</script>

<ul class="m-0 pb-2.5 pt-2.5 p-is-0 flex w-full">
  <NavLinkItem class="menu-title" href="/" text={name} />
  {#each navLinks as { href, text, icon, dropbox } (href)}
    {#if !dropbox?.enable}
      <NavLinkItem
        {href}
        {text}
        {icon}
        class="desktop-only inline-block before:rounded-0.5 before:bg-current before:h-0.75 before:w-0 before:content-empty before:transform-translate-x--50% before:transition-all before:transition-duration-400 before:transition-ease-in-out before:bottom-0 before:left-50% before:absolute hover:before:w-60%"
      />
    {:else}
      <DropBox
        navLinks={dropbox?.items ?? []}
        {icon}
        rootText={text}
        class="desktop-only inline-block"
      />
    {/if}
  {/each}
</ul>

<style>
  :global(.menu-title) {
    display: block;
  }

  :global(.desktop-only) {
    display: none;
  }

  @media (min-width: 821px) {
    :global(.menu-title) {
      display: inline-block;
    }

    :global(.desktop-only) {
      display: inline-block;
    }
  }
</style>
